@baseUrl = http://127.0.0.1:3000 

#MESSAGENS
###
GET {{baseUrl}}/messages

###
GET {{baseUrl}}/messages/1

###
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "Mensagem": "Aqui uma mensagem",
  "tipo": "texto"
}

###
PATCH  {{baseUrl}}/messages/1
Content-Type: application/json

{
  "Mensagem": "Aqui uma mensagem",
  "tipo": "texto"
}